### ISSUE TITLE
Need help in installing liteqube

### ISSUE THREAD

**Issue by tampos4** [a-barinov/liteqube#2]
1. Fresh Qubes 4.1.0 installed.
2. Downloaded and transferred liteqube-0.91.tar.gz to dom0 and unpacked it.
3. Run `install.sh` script in '1.Base'.
![45975bcf-2add-44c3-bd91-169c361e7c5c](https://user-images.githubusercontent.com/103326242/162634287-b16a05c7-fc61-4158-857e-327a0cd86704.png)
![898c0895-131c-4dae-8bc6-4667b22f5fb2](https://user-images.githubusercontent.com/103326242/162634306-1674e3ed-adc6-41f9-b031-725c71e69a5a.png)

Everytime it stops at this point.

What am I doing wrong?

**Comment by a-barinov** [comment]
Apologies, turned out git ignored an empty dir that was supposed to be present in the tarball. Fixed with the latest commit.

**Comment by invalid-error** [comment]
Unfortunately, it is still present in liteqube-0.91.tar.gz. Could you please double check?
Suggestion, what about having a hash for the tar?

**Comment by a-barinov** [comment]
First, many thanks for testing! I discovered that there were around 10 dirs missing, fixed that in a couple of commits. I don't intend to silently update 0.91 though but rather release 0.92 which is almost there and is pending testing (I found a test laptop to run fresd installs on) and release notes writing.

You can either clone the repo and install from it (should work but full-cycle testing is still pending) or wait for a week or so until 0.92 will get released. That one will install for you, I promise!

**Comment by invalid-error** [comment]
Thanks for the prompt feedback. I will wait a week (no urgency) and use the time to review the script more deeply...

I have a free notebook for testing your setup and I would like to contribute at least for testing your liteqube.
